### ISSUE TITLE
Step1: stdinから入力を受け付けて表示する

### ISSUE THREAD

**Issue by RY-2718** [RY-2718/mysh#1]
## 目的
まずはユーザからの入力をきちんと受け取ることができなければその後の処理もクソもない．
stdinから文字列の入力を受け取ることでその後の実装ができるようにする．

## 仕様
- プロンプトは `mysh $ `
- Ctrl-Cされるまで無限にループする
- 入力文字数は最大256文字
    - 最大文字数は `#define` 文で記述する．マジックナンバー死すべし．慈悲はない．

## task list
- [ ] まずはブランチを切ろう．凝らないなら `step1` とかでいいし，git flowとかそういうのに乗りたかったら `feature/get_input` とかそんな感じでもいい．
- [ ] そしたらガリガリ実装……する前にどう実装するか考えよう．鼻歌交じりにできそうならそのまま進めればいい．
- [ ] ちょっと難しいかな？と思った場合は目標を更に小さい目標に分割しよう．例えば文字列の入力を受け取って変数に格納するにはどうすればいい？また，ループの際に気をつけるべきことはあるか？

## 目標
- 仕様が満たされるように，文字列の入力を受け取ることができるようになる．
- C言語で踏みがちな罠を踏んでいない状態になる．まあここらへんはPRで先輩にレビューしてもらうといいと思います．
